### ISSUE TITLE
All files relating to config should be linked to files in odroid_setup

### ISSUE THREAD

**Issue by justinthomas** [justinthomas/odroid_setup#2]
For example, in odroid_setup.sh, we currently echo lines to files such as ~/.bash_profile and /etc/network/interfaces. Instead, we should just make symlinks to files that have the config in odroid_setup.

**Comment by andrewblock01** [comment]
Addressed by 2166a1dbe1c59634ff85c57081e980baa16ebf75 and 107cb334b5d5d5a29077e1fe90f995b542be42f7.
